CREATE TABLE PRODUCTS 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(20) 
, TYPE NUMBER NOT NULL 
, PRICE NUMBER DEFAULT 0 NOT NULL 
, QUANTITY NUMBER DEFAULT 1 NOT NULL 
, STATUS VARCHAR2(20) 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE PRODUCT_TYPE 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(50) 
, CONSTRAINT PRODUCT_TYPE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

alter table PRODUCTS add constraint PRODUCT_TYPE_FK foreign key(TYPE) references PRODUCT_TYPE(ID);

CREATE TABLE CUSTOMERS 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(50) 
, PID VARCHAR2(20) NOT NULL 
, DATE_OF_BIRTH DATE 
, ADDRESS VARCHAR2(20) 
, STATUS VARCHAR2(20) 
, CONSTRAINT CUSTOMERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE ORDERS 
(
  ID NUMBER NOT NULL 
, PRODUCTS NUMBER 
, QUANTITIES NUMBER 
, OVERALL_PRICE NUMBER 
, CUSTOMER NUMBER 
, PURCHASE_DATE DATE 
, STATUS VARCHAR2(20) 
, CONSTRAINT ORDERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE PRODUCT_LIST 
(
  ID VARCHAR2(20) NOT NULL 
, ORDER_ID NUMBER 
, PRODUCT_ID NUMBER 
, QUANTITY NUMBER 
, CONSTRAINT PRODUCT_LIST_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

alter table PRODUCT_LIST add constraint ORDER_FK foreign key(ORDER_ID) references ORDERS(ID);
alter table PRODUCT_LIST add constraint PRODUCT_FK foreign key(PRODUCT_ID) references PRODUCTS(ID);
alter table ORDERS add constraint CUSTOMER_FK foreign key(CUSTOMER) references CUSTOMERS(ID);

ALTER TABLE Customers MODIFY (
   address varchar2(100)
);

alter table ORDERS drop column PRODUCTS;
alter table ORDERS drop column QUANTITIES;
ALTER TABLE products RENAME CONSTRAINT table1_pk TO products_pk;

//customer - add created_by/user owner
//overall price in product_list for every product?
