INSERT INTO "WEBSTORE"."PRODUCT_TYPE" (ID, NAME) VALUES ('1', 'computer')
INSERT INTO "WEBSTORE"."PRODUCT_TYPE" (ID, NAME) VALUES ('2', 'phone')
INSERT INTO "WEBSTORE"."PRODUCT_TYPE" (ID, NAME) VALUES ('3', 'drink')

INSERT INTO "WEBSTORE"."PRODUCTS" (ID, NAME, TYPE, PRICE, QUANTITY, STATUS) VALUES ('1', 'model01', '1', '1000', '5', 'Active')
INSERT INTO "WEBSTORE"."PRODUCTS" (ID, NAME, TYPE, PRICE, QUANTITY, STATUS) VALUES ('2', 'model02', '1', '900.23', '2', 'Inactive')
INSERT INTO "WEBSTORE"."PRODUCTS" (ID, NAME, TYPE, PRICE, QUANTITY, STATUS) VALUES ('3', 'model01', '2', '1234.56', '10', 'Active')
INSERT INTO "WEBSTORE"."PRODUCTS" (ID, NAME, TYPE, PRICE, QUANTITY, STATUS) VALUES ('4', 'new_product', '3', '9.99', '20', 'Inactive')
INSERT INTO "WEBSTORE"."PRODUCTS" (ID, NAME, TYPE, PRICE, QUANTITY, STATUS) VALUES ('5', 'new_product 02', '3', '28009.99', '1', 'Active')

INSERT INTO "WEBSTORE"."CUSTOMERS" (ID, NAME, PID, DATE_OF_BIRTH, ADDRESS, STATUS) VALUES ('1', 'Customer Name', '0123CN', TO_DATE('1987-11-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'City,1 "Street" Str.', 'Active')
INSERT INTO "WEBSTORE"."CUSTOMERS" (ID, NAME, PID, DATE_OF_BIRTH, ADDRESS, STATUS) VALUES ('2', 'Other Customer Name', '0123ON', TO_DATE('1987-11-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'City,1 "Street" Str.', 'Inactive')

INSERT INTO "WEBSTORE"."ORDERS" (ID, OVERALL_PRICE, CUSTOMER, PURCHASE_DATE, STATUS) VALUES ('1', '1000', '1', TO_DATE('2016-04-02 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Active')

INSERT INTO "WEBSTORE"."PRODUCT_LIST" (ID, ORDER_ID, PRODUCT_ID, QUANTITY) VALUES ('1', '1', '1', '2')
INSERT INTO "WEBSTORE"."PRODUCT_LIST" (ID, ORDER_ID, PRODUCT_ID, QUANTITY) VALUES ('2', '1', '2', '2')
