CREATE TABLE PRODUCTS 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(20) 
, TYPE NUMBER NOT NULL 
, PRICE NUMBER DEFAULT 0 NOT NULL 
, QUANTITY NUMBER DEFAULT 1 NOT NULL 
, STATUS VARCHAR2(20) 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE PRODUCT_TYPE 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(50) 
, CONSTRAINT PRODUCT_TYPE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

alter table PRODUCTS add constraint PRODUCT_TYPE_FK foreign key(TYPE) references PRODUCT_TYPE(ID);

CREATE TABLE CUSTOMERS 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(50) 
, PID VARCHAR2(20) NOT NULL 
, DATE_OF_BIRTH DATE 
, ADDRESS VARCHAR2(20) 
, STATUS VARCHAR2(20) 
, CONSTRAINT CUSTOMERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE ORDERS 
(
  ID NUMBER NOT NULL 
, PRODUCTS NUMBER 
, QUANTITIES NUMBER 
, OVERALL_PRICE NUMBER 
, CUSTOMER NUMBER 
, PURCHASE_DATE DATE 
, STATUS VARCHAR2(20) 
, CONSTRAINT ORDERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE PRODUCT_LIST 
(
  ID VARCHAR2(20) NOT NULL 
, ORDER_ID NUMBER 
, PRODUCT_ID NUMBER 
, QUANTITY NUMBER 
, CONSTRAINT PRODUCT_LIST_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

alter table PRODUCT_LIST add constraint ORDER_FK foreign key(ORDER_ID) references ORDERS(ID);
alter table PRODUCT_LIST add constraint PRODUCT_FK foreign key(PRODUCT_ID) references PRODUCTS(ID);
alter table ORDERS add constraint CUSTOMER_FK foreign key(CUSTOMER) references CUSTOMERS(ID);

ALTER TABLE Customers MODIFY (
   address varchar2(100)
);

alter table ORDERS drop column PRODUCTS;
alter table ORDERS drop column QUANTITIES;
ALTER TABLE products RENAME CONSTRAINT table1_pk TO products_pk;

CREATE SEQUENCE product_type_seq
      INCREMENT BY 1
      START WITH 1
      NOMAXVALUE
      NOCYCLE
      CACHE 10;

CREATE SEQUENCE product_seq
      INCREMENT BY 1
      START WITH 1
      NOMAXVALUE
      NOCYCLE
      CACHE 10;

ALTER TABLE product_type ADD CONSTRAINT product_type_name_unique UNIQUE (name);

ALTER SEQUENCE product_type_seq
   NOCACHE;

ALTER SEQUENCE product_seq
   NOCACHE;

ALTER SEQUENCE product_type_seq
   CACHE 2;

ALTER SEQUENCE product_seq
   CACHE 2;

CREATE TABLE ROLES (
    ID NUMBER NOT NULL ENABLE, 
	ROLE VARCHAR2(50 BYTE), 
	CONSTRAINT ROLES_PK PRIMARY KEY (ID)
);

CREATE TABLE USERS 
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(50) 
, USERNAME VARCHAR2(20) 
, PASSWORD VARCHAR2(100) 
, STATUS VARCHAR2(20) 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE USER_ROLES 
(
  USER_ID NUMBER 
, ROLE_ID NUMBER 
);

ALTER TABLE Users MODIFY (
   name number
);

alter table USERS drop column NAME;

UPDATE USERS SET PASSWORD = 'c20ad4d76fe97759aa27a0c99bff6710' WHERE USERNAME LIKE 'user%';

CREATE TABLE USER_CUSTOMERS 
(
  USER_ID NUMBER 
, CUSTOMER_ID NUMBER 
);

alter table USER_CUSTOMERS add constraint USER_FK foreign key(USER_ID) references USERS(ID);
alter table USER_CUSTOMERS add constraint CUSTOMERS_FK foreign key(CUSTOMER_ID) references CUSTOMERS(ID);

alter table USER_ROLES add constraint USER_FK2 foreign key(USER_ID) references USERS(ID);
alter table USER_ROLES add constraint ROLE_FK foreign key(ROLE_ID) references ROLES(ID);
